version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_URI=mongodb://127.0.0.1:27017/Users
    depends_on:
      - mongo

  mongo:
    container_name: mongodb_container
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: