name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Chekout do código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
          node-version: '20.x'
      
    - name: Instalando dependencias
      run: npm install
      working-directory: notes_project
  
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Chekout do código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
          node-version: '20.x'

    - name: Instalar Dependencias
      run: npm install
      working-directory: notes_project  

    - name: Build Docker image
      run: docker build -t myapp .
      working-directory: notes_project  

    - name: Run Docker Compose
      run: docker-compose up -d
      working-directory: notes_project  