name: CI

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Chekout do código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
          node-version: '16.X'
    
    - name: Debug current directory
      run: pwd  # Mostra o diretório atual
          # Se o diretório atual for diferente do esperado, ajuste o caminho
          
    - name: Navigate to notes-project directory
      run: cd cd User_Diary/notes-project   
     
    - name: Debug current directory after navigation
      run: pwd  # Mostra o diretório atual após a navegação
           

    - name: Instalar Dependências
      run: npm install
  
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Chekout do código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
          node-version: '20.x'

    - name: Instalar Dependencias
      run: npm install

    - name: Executar Testes
      run: npm test

    - name: Instalar http-server
      run: npm install -g http-server

    - name: Iniciar http-server
      run: http-server -p 3000 -d false &

    - name: Esperar pelo http-server
      run: sleep 5

    - name: Executar Testes Cypress
      run: npx cypress run --config baseUrl=http://localhost:3000
